In [ ]:
import pandas as pd

data = {
    "name": ["Ali", "Ali", "Sara", "Sara", "Rahul", "Rahul", "Anita", "Anita"],
    "subject": ["Math", "Science", "Math", "Science", "Math", "Science", "Math", "Science"],
    "score": [78, 85, 92, 88, 65, 70, 95, 90]
}

df = pd.DataFrame(data)
df.to_csv("students_data.csv", index=False)

print("CSV file created")

CSV file created

In [ ]:
import pandas as pd

df = pd.read_csv("students_data.csv")
df

    name  subject  score
0    Ali     Math     78
1    Ali  Science     85
2   Sara     Math     92
3   Sara  Science     88
4  Rahul     Math     65
5  Rahul  Science     70
6  Anita     Math     95
7  Anita  Science     90

In [ ]:
high_scores = df[df["score"] > 80]
high_scores

    name  subject  score
1    Ali  Science     85
2   Sara     Math     92
3   Sara  Science     88
6  Anita     Math     95
7  Anita  Science     90

In [ ]:
avg_scores = df.groupby("subject")["score"].mean()
avg_scores

subject
Math       82.50
Science    83.25
Name: score, dtype: float64

In [ ]:
sorted_df = df.sort_values(by="score", ascending=False)
sorted_df

    name  subject  score
6  Anita     Math     95
2   Sara     Math     92
7  Anita  Science     90
3   Sara  Science     88
1    Ali  Science     85
0    Ali     Math     78
5  Rahul  Science     70
4  Rahul     Math     65

Insight 1:

Students perform better in Science compared to Math based on average scores.

Insight 2:

Anita is the top-performing student with the highest scores.

In [ ]:
top_student = df.loc[df["score"].idxmax()]
top_student

name       Anita
subject     Math
score         95
Name: 6, dtype: object